appname = awesomeProject1
httpport = 8080
runmode = dev
copyrequestbody = true

# mysql
db_driver = mysql
db_user = root
db_password = ${db_password}
db_host = ${db_host}
db_port = 3306
db_name = test